### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by rpryzant** [Electrostatics/apbs-pdb2pqr#466]
In ``pdb2pqr/propka30/Source/protein.py``, ``getPHopt()``, line 628, there might be an uncaught exception.

``pH_opt`` can be referenced before assignment. This happened to me. Stack trace: 

```
Traceback (most recent call last):
  File "<string>", line 62, in <module>
  File "/home/kyle/tmp/build/pdb2pqr/out00-PYZ.pyz/main", line 740, in mainCommand
  File "/home/kyle/tmp/build/pdb2pqr/out00-PYZ.pyz/main", line 339, in runPDB2PQR
  File "/home/kyle/tmp/build/pdb2pqr/out00-PYZ.pyz/src.routines", line 1596, in runPROPKA
  File "/home/kyle/tmp/build/pdb2pqr/out00-PYZ.pyz/propka30.Source.protein", line 581, in writePKA
  File "/home/kyle/tmp/build/pdb2pqr/out00-PYZ.pyz/propka30.Source.output", line 174, in writePKA
  File "/home/kyle/tmp/build/pdb2pqr/out00-PYZ.pyz/propka30.Source.output", line 283, in getFoldingProfileSection
  File "/home/kyle/tmp/build/pdb2pqr/out00-PYZ.pyz/propka30.Source.protein", line 629, in getPHopt
UnboundLocalError: local variable 'pH_opt' referenced before assignment
```

**Comment by keith923** [comment]
This is part of PROPKA, not PDB2PQR.  So while their code should maybe be a bit more robust, it may be that PDB2PQR is doing something wrong when calling their code.  It's hard to tell though, just given what you have supplied above.  Can you let us know how to reproduce the problem?

Also, you may want to submit a bug report to the PROPKA folks.

**Comment by rpryzant** [comment]
Ah, thanks for the info.

I was trying to run every structure in the PDB through pdb2pqr. Not sure exactly which structures caused the hiccup because all of my threads were writing to a pooled stderr. When I track that down, though, I'll be sure to ping the PROPKA folks about it.
